EXTRA_TRANSLATIONS = {
    "zh": {
        "fan": "性能", "lighting": "灯效", "mux": "显卡切换", "settings": "设置", "keyboard": "快捷键", "app_profiles": "应用配置",
        "fan_control": "风扇控制", "system_status": "系统状态", "power_profile": "电源模式", "fan_mode": "风扇模式",
        "fan_curve": "风扇曲线", "all_sensors": "所有传感器", "fan_disabled": "风扇控制不可用", "checking": "检查中...",
        "no_ppd": "无 PPD", "active_profile": "当前模式", "mode": "模式", "active": "启用", "inactive": "停用",
        "saver": "节能", "balanced": "平衡", "performance": "性能", "auto": "自动", "max": "最大", "custom": "自定义", "standard": "标准",
        "curve_desc": "拖动节点以自定义风扇曲线。X：温度 (°C)，Y：风扇转速 (%)", "no_sensor": "未找到传感器数据",
        "keyboard_lighting": "键盘灯效", "keyboard_light": "键盘灯", "zone": "区域", "all_zones": "全部",
        "effect": "效果", "direction": "方向", "speed": "速度", "brightness": "亮度",
        "static_eff": "静态", "breathing": "呼吸", "wave": "波浪", "cycle": "循环", "ltr": "左 → 右", "rtl": "右 → 左",
        "win_lock": "锁定 Windows 键", "keyboard_shortcuts": "快捷键", "special_keys": "特殊按键",
        "omen_key": "Omen 键", "victus_key": "Omen 键", "calc_key": "计算器键", "prt_sc_fix": "修复截屏键 (PrtSc)",
        "prt_sc_desc": "使 PrtSc 键作为真正的 Print Screen 键工作。", "f1_fix": "修复 F1 键",
        "f1_desc": "使 F1 键作为标准 F1 键工作。", "apply_shortcuts": "应用更改",
        "shortcuts_desc": "您可以在此处永久更改笔记本某些键的行为。", "hwdb_applied": "键盘修复已成功应用。",
        "macros_title": "宏与命令", "macros_desc": "分配终端命令或点击图标选择应用程序。",
        "term_cmd": "终端命令...", "choose_app": "选择已安装的应用程序", "sel_app": "选择应用程序",
        "or_custom_cmd": "或输入自定义 bash 命令...", "mux_switch": "显卡切换 (MUX)", "gpu_info": "显卡信息",
        "gpu_card": "显卡", "driver_ver": "驱动版本", "gpu_mode": "显卡模式", "hybrid": "混合",
        "discrete": "独立显卡", "integrated": "集成显卡", "hybrid_desc": "NVIDIA Optimus (混合)",
        "discrete_desc": "NVIDIA GeForce RTX", "integrated_desc": "Intel Iris Xe / AMD Radeon",
        "gpu_checking": "正在检查显卡模式...", "restart_warn": "需要重启系统以更改显卡模式。",
        "mux_not_found": "未找到 MUX 工具", "mux_install_hint": "必须安装 envycontrol、supergfxctl 或 prime-select。",
        "restart": "重启", "restart_confirm": "系统将重启以更改显卡模式为 '{mode}'。继续？",
        "mode_set": "模式已设为 '{mode}'。正在重启...", "mux_backend_label": "MUX 后端工具", "mux_auto": "自动检测",
        "appearance": "外观", "theme": "主题", "lang_label": "语言", "dark": "深色", "light": "浅色", "system": "系统默认",
        "updates": "更新", "current_ver": "当前版本", "dashboard": "仪表板", "quick_status": "快速状态",
        "hardware_profile": "硬件配置", "resources": "资源", "quick_actions": "快捷操作", "clean_memory": "清理内存",
        "max_fan": "最大风扇", "eco_mode": "节能模式", "go_performance": "前往性能设置", "fan_metric": "风扇",
        "disk": "磁盘", "ram": "内存", "cpu_load_30s": "CPU 负载 (最近30秒)", "power_profile_label": "电源模式",
        "fan_mode_label": "风扇模式", "gpu_mux_label": "显卡 / MUX", "battery": "电池", "ac_power": "交流电源",
        "health": "健康度", "power_saver_lbl": "节能", "balanced_lbl": "平衡", "performance_lbl": "性能",
        "check_update": "检查更新", "download": "下载", "sys_info": "系统信息", "computer": "计算机", "kernel": "内核",
        "os_name": "操作系统", "arch": "架构", "driver_status": "驱动状态", "loaded": "✓ 已加载", "not_loaded": "✗ 未加载",
        "developer": "开发者", "home_subtitle": "选择一个模块继续", "debug_info_title": "诊断与调试",
        "show_debug_info": "显示调试信息", "copy_debug_log": "复制调试信息", "copied_to_clipboard": "已复制到剪贴板",
        "create_github_issue": "创建 GitHub Issue", "cpu_tuning": "CPU 调优", "undervolt": "降压 (Undervolt)",
        "cpu_curves": "CPU 曲线", "custom_curve": "自定义曲线", "tcc_offset": "TCC 偏移 (降温)",
        "power_tuning": "电源与电压", "power_tuning_desc": "配置高级电压和温度限制。",
        "undervolt_label": "CPU 降压", "undervolt_desc": "较低的电压可让您的处理器运行更凉爽。",
        "tcc_label": "TCC 偏移 (温度限制)", "tcc_desc": "降低最大运行温度。",
        "power_limits_label": "电源限制 (PL1 / PL2)", "power_limits_desc": "配置长期 (PL1) 和短期 (PL2) 功率限制。",
        "pl1_w": "长期功率限制 (PL1 - 瓦)", "pl2_w": "短期功率限制 (PL2 - 瓦)",
        "apply_power": "应用设置", "power_applied": "电源和电压设置已成功应用。",
        "unsupported_power": "您的系统不支持这些高级电源调优功能。", "troubleshooting_dump": "故障排除与转储",
        "thanks_for_using": "感谢您使用 OmenCtl。", "send_to_github": "发送报告至 Github Issue", "back": "返回"
    },
    "es": {
        "fan": "Rendimiento", "lighting": "Iluminación", "mux": "MUX", "settings": "Ajustes", "keyboard": "Atajos", "app_profiles": "Perfiles",
        "fan_control": "Control del Ventilador", "system_status": "ESTADO DEL SISTEMA", "power_profile": "PERFIL DE ENERGÍA", "fan_mode": "MODO",
        "fan_curve": "CURVA DEL VENTILADOR", "all_sensors": "Todos los Sensores", "fan_disabled": "Control de ventilador no disponible", "checking": "Comprobando...",
        "no_ppd": "Sin PPD", "active_profile": "Perfil activo", "mode": "Modo", "active": "Activo", "inactive": "Inactivo",
        "saver": "Ahorro", "balanced": "Equilibrado", "performance": "Rendimiento", "auto": "Automático", "max": "Máximo", "custom": "Personalizado", "standard": "Estándar",
        "curve_desc": "Arrastra los puntos para personalizar la curva. X: Temperatura (°C), Y: Velocidad (%)", "no_sensor": "No se encontraron sensores",
        "keyboard_lighting": "Iluminación del Teclado", "keyboard_light": "LUZ DEL TECLADO", "zone": "Zona", "all_zones": "Todas",
        "effect": "EFECTO", "direction": "DIRECCIÓN", "speed": "VELOCIDAD", "brightness": "BRILLO",
        "static_eff": "Estático", "breathing": "Respiración", "wave": "Onda", "cycle": "Ciclo", "ltr": "Izq → Der", "rtl": "Der → Izq",
        "win_lock": "Bloqueo de tecla Super", "keyboard_shortcuts": "Atajos", "special_keys": "TECLAS ESPECIALES",
        "omen_key": "Tecla Omen", "victus_key": "Tecla Omen", "calc_key": "Calculadora", "prt_sc_fix": "Reparar Print Screen",
        "prt_sc_desc": "Hace que PrtSc funcione como un botón real.", "f1_fix": "Reparar tecla F1",
        "f1_desc": "Hace que F1 funcione como estándar.", "apply_shortcuts": "Aplicar Cambios",
        "shortcuts_desc": "Cambia permanentemente el comportamiento de ciertas teclas.", "hwdb_applied": "Reparaciones aplicadas con éxito.",
        "macros_title": "Macros y Comandos", "macros_desc": "Asigna comandos o elige una aplicación.",
        "term_cmd": "Comando de terminal...", "choose_app": "Elegir aplicación instalada", "sel_app": "Seleccionar Aplicación",
        "or_custom_cmd": "O escribir un comando bash...", "mux_switch": "Interruptor MUX", "gpu_info": "INFO GPU",
        "gpu_card": "Tarjeta Gráfica", "driver_ver": "Controlador", "gpu_mode": "MODO GPU", "hybrid": "Híbrido",
        "discrete": "Dedicada", "integrated": "Integrada", "hybrid_desc": "NVIDIA Optimus",
        "discrete_desc": "NVIDIA GeForce RTX", "integrated_desc": "Gráficos Intel/AMD",
        "gpu_checking": "Comprobando modo GPU...", "restart_warn": "Es necesario reiniciar el sistema.",
        "mux_not_found": "No se encontró herramienta MUX", "mux_install_hint": "Debe instalar envycontrol, supergfxctl o prime-select.",
        "restart": "Reiniciar", "restart_confirm": "El sistema se reiniciará. ¿Continuar?",
        "mode_set": "Modo configurado en '{mode}'. Reiniciando...", "mux_backend_label": "Backend MUX", "mux_auto": "Auto Detectar",
        "appearance": "APARIENCIA", "theme": "Tema", "lang_label": "Idioma", "dark": "Oscuro", "light": "Claro", "system": "Sistema",
        "updates": "ACTUALIZACIONES", "current_ver": "Versión actual", "dashboard": "Panel de Control", "quick_status": "Estado Rápido",
        "hardware_profile": "Perfil de Hardware", "resources": "Recursos", "quick_actions": "Acciones", "clean_memory": "Limpiar Memoria",
        "max_fan": "Ventilador MÁX", "eco_mode": "Modo Eco", "go_performance": "Ir a Rendimiento", "fan_metric": "Ventilador",
        "disk": "Disco", "ram": "RAM", "cpu_load_30s": "Carga CPU (30s)", "power_profile_label": "Perfil Energía",
        "fan_mode_label": "Modo Ventilador", "gpu_mux_label": "GPU / MUX", "battery": "Batería", "ac_power": "Corriente AC",
        "health": "Salud", "power_saver_lbl": "Ahorro", "balanced_lbl": "Equilibrado", "performance_lbl": "Rendimiento",
        "check_update": "Buscar Actualizaciones", "download": "Descargar", "sys_info": "INFO DEL SISTEMA", "computer": "Ordenador", "kernel": "Kernel",
        "os_name": "Sistema Operativo", "arch": "Arquitectura", "driver_status": "ESTADO DEL CONTROLADOR", "loaded": "✓ Cargado", "not_loaded": "✗ No Cargado",
        "developer": "Desarrollador", "home_subtitle": "Elija un módulo para continuar", "debug_info_title": "Diagnóstico y Depuración",
        "show_debug_info": "Mostrar Depuración", "copy_debug_log": "Copiar Registro", "copied_to_clipboard": "Copiado al portapapeles",
        "create_github_issue": "Crear Issue en GitHub", "cpu_tuning": "Ajuste CPU", "undervolt": "Undervolt",
        "cpu_curves": "Curvas de CPU", "custom_curve": "Curva Personalizada", "tcc_offset": "Offset TCC",
        "power_tuning": "Energía y Voltaje", "power_tuning_desc": "Configure límites avanzados.",
        "undervolt_label": "Undervolt CPU", "undervolt_desc": "Permite que el procesador funcione más frío.",
        "tcc_label": "Límite TCC", "tcc_desc": "Reduce la temperatura máxima de funcionamiento.",
        "power_limits_label": "Límites de Energía (PL1 / PL2)", "power_limits_desc": "Configurar límites de vatios a largo (PL1) y corto (PL2) plazo.",
        "pl1_w": "Límite a largo plazo (PL1 - W)", "pl2_w": "Límite a corto plazo (PL2 - W)",
        "apply_power": "Aplicar Ajustes", "power_applied": "Ajustes aplicados correctamente.",
        "unsupported_power": "Su sistema no admite ajustes de energía avanzados.", "troubleshooting_dump": "Solución de Problemas",
        "thanks_for_using": "Gracias por usar OmenCtl.", "send_to_github": "Enviar a Github", "back": "Atrás"
    },
    "fr": {
        "fan": "Performances", "lighting": "Éclairage", "mux": "MUX", "settings": "Paramètres", "keyboard": "Raccourcis", "app_profiles": "Profils",
        "fan_control": "Contrôle Ventilateur", "system_status": "ÉTAT SYSTÈME", "power_profile": "PROFIL", "fan_mode": "MODE",
        "fan_curve": "COURBE", "all_sensors": "Capteurs", "fan_disabled": "Indisponible", "checking": "Vérification...",
        "no_ppd": "Pas de PPD", "active_profile": "Profil actif", "mode": "Mode", "active": "Actif", "inactive": "Inactif",
        "saver": "Éco", "balanced": "Équilibré", "performance": "Perf", "auto": "Auto", "max": "Max", "custom": "Personnalisé", "standard": "Standard",
        "curve_desc": "Faites glisser les points. X : Température, Y : Vitesse", "no_sensor": "Aucun capteur",
        "keyboard_lighting": "Éclairage Clavier", "keyboard_light": "LUMIÈRE CLAVIER", "zone": "Zone", "all_zones": "Toutes",
        "effect": "EFFET", "direction": "DIRECTION", "speed": "VITESSE", "brightness": "LUMINOSITÉ",
        "static_eff": "Statique", "breathing": "Respiration", "wave": "Vague", "cycle": "Cycle", "ltr": "G → D", "rtl": "D → G",
        "win_lock": "Verrouiller Super", "keyboard_shortcuts": "Raccourcis", "special_keys": "TOUCHES",
        "omen_key": "Touche Omen", "victus_key": "Touche Omen", "calc_key": "Calculatrice", "prt_sc_fix": "Fixer Impr. Écran",
        "prt_sc_desc": "La touche Impr Écran fonctionne normalement.", "f1_fix": "Fixer F1",
        "f1_desc": "La touche F1 fonctionne normalement.", "apply_shortcuts": "Appliquer",
        "shortcuts_desc": "Modifiez définitivement le comportement des touches.", "hwdb_applied": "Succès.",
        "macros_title": "Macros", "macros_desc": "Assignez des commandes ou une application.",
        "term_cmd": "Commande terminal...", "choose_app": "Choisir application", "sel_app": "Sélectionner Application",
        "or_custom_cmd": "Ou tapez une commande bash...", "mux_switch": "MUX", "gpu_info": "INFO GPU",
        "gpu_card": "Carte Graphique", "driver_ver": "Pilote", "gpu_mode": "MODE GPU", "hybrid": "Hybride",
        "discrete": "Dédiée", "integrated": "Intégrée", "hybrid_desc": "NVIDIA Optimus",
        "discrete_desc": "NVIDIA GeForce RTX", "integrated_desc": "Intel Iris / AMD Radeon",
        "gpu_checking": "Vérification...", "restart_warn": "Redémarrage requis.",
        "mux_not_found": "Outil MUX introuvable", "mux_install_hint": "Installez envycontrol, etc.",
        "restart": "Redémarrer", "restart_confirm": "Redémarrer pour appliquer ?",
        "mode_set": "Mode configuré. Redémarrage...", "mux_backend_label": "Outil MUX", "mux_auto": "Auto",
        "appearance": "APPARENCE", "theme": "Thème", "lang_label": "Langue", "dark": "Sombre", "light": "Clair", "system": "Système",
        "updates": "MISES À JOUR", "current_ver": "Version", "dashboard": "Tableau de Bord", "quick_status": "Statut",
        "hardware_profile": "Profil", "resources": "Ressources", "quick_actions": "Actions", "clean_memory": "Nettoyer Mémoire",
        "max_fan": "Ventilateur Max", "eco_mode": "Mode Éco", "go_performance": "Aller à Performances", "fan_metric": "Ventilo",
        "disk": "Disque", "ram": "RAM", "cpu_load_30s": "Charge CPU", "power_profile_label": "Profil",
        "fan_mode_label": "Mode Ventilo", "gpu_mux_label": "GPU / MUX", "battery": "Batterie", "ac_power": "Secteur",
        "health": "Santé", "power_saver_lbl": "Éco", "balanced_lbl": "Équilibré", "performance_lbl": "Perf",
        "check_update": "Chercher Mises à jour", "download": "Télécharger", "sys_info": "SYSTÈME", "computer": "PC", "kernel": "Noyau",
        "os_name": "OS", "arch": "Arch", "driver_status": "PILOTES", "loaded": "✓ Chargé", "not_loaded": "✗ Non Chargé",
        "developer": "Développeur", "home_subtitle": "Choisissez un module", "debug_info_title": "Débogage",
        "show_debug_info": "Afficher Débogage", "copy_debug_log": "Copier Débogage", "copied_to_clipboard": "Copié",
        "create_github_issue": "Créer Issue GitHub", "cpu_tuning": "Tuning CPU", "undervolt": "Undervolt",
        "cpu_curves": "Courbes CPU", "custom_curve": "Courbe Perso", "tcc_offset": "Offset TCC",
        "power_tuning": "Énergie", "power_tuning_desc": "Paramètres avancés.",
        "undervolt_label": "Undervolt CPU", "undervolt_desc": "Le processeur chauffe moins.",
        "tcc_label": "Offset TCC", "tcc_desc": "Baisse la température max.",
        "power_limits_label": "Limites (PL1 / PL2)", "power_limits_desc": "Config PL1 et PL2.",
        "pl1_w": "Limite PL1 (W)", "pl2_w": "Limite PL2 (W)",
        "apply_power": "Appliquer", "power_applied": "Succès.",
        "unsupported_power": "Non supporté.", "troubleshooting_dump": "Dépannage",
        "thanks_for_using": "Merci.", "send_to_github": "Envoyer sur GitHub", "back": "Retour"
    },
    "hi": {
        "fan": "प्रदर्शन", "lighting": "लाइटिंग", "mux": "MUX", "settings": "सेटिंग्स", "keyboard": "शॉर्टकट", "app_profiles": "ऐप प्रोफाइल",
        "fan_control": "फैन कंट्रोल", "system_status": "सिस्टम स्थिति", "power_profile": "पावर प्रोफाइल", "fan_mode": "फैन मोड",
        "fan_curve": "फैन कर्व", "all_sensors": "सभी सेंसर", "fan_disabled": "फैन कंट्रोल उपलब्ध नहीं", "checking": "जांच की जा रही है...",
        "no_ppd": "कोई PPD नहीं", "active_profile": "सक्रिय प्रोफाइल", "mode": "मोड", "active": "सक्रिय", "inactive": "निष्क्रिय",
        "saver": "पावर सेवर", "balanced": "संतुलित", "performance": "प्रदर्शन", "auto": "ऑटो", "max": "अधिकतम", "custom": "कस्टम", "standard": "मानक",
        "curve_desc": "वक्र बदलने के लिए बिंदु खींचें।", "no_sensor": "कोई सेंसर डेटा नहीं मिला",
        "keyboard_lighting": "कीबोर्ड लाइटिंग", "keyboard_light": "कीबोर्ड लाइट", "zone": "ज़ोन", "all_zones": "सभी",
        "effect": "प्रभाव", "direction": "दिशा", "speed": "गति", "brightness": "चमक",
        "static_eff": "स्थिर", "breathing": "सांस लेना", "wave": "लहर", "cycle": "चक्र", "ltr": "बाएँ → दाएँ", "rtl": "दाएँ → बाएँ",
        "win_lock": "सुपर की लॉक", "keyboard_shortcuts": "शॉर्टकट्स", "special_keys": "विशेष कुंजियाँ",
        "omen_key": "ओमेन की", "victus_key": "ओमेन की", "calc_key": "कैलकुलेटर", "prt_sc_fix": "PrtSc ठीक करें",
        "prt_sc_desc": "PrtSc को वास्तविक प्रिंट स्क्रीन बनाता है।", "f1_fix": "F1 ठीक करें",
        "f1_desc": "F1 को मानक F1 बनाता है।", "apply_shortcuts": "लागू करें",
        "shortcuts_desc": "कुंजियों के व्यवहार को स्थायी रूप से बदलें।", "hwdb_applied": "सफलतापूर्वक लागू हुआ।",
        "macros_title": "मैक्रोज़ और कमांड", "macros_desc": "कमांड असाइन करें या ऐप चुनें।",
        "term_cmd": "टर्मिनल कमांड...", "choose_app": "ऐप चुनें", "sel_app": "एप्लिकेशन चुनें",
        "or_custom_cmd": "या कमांड लिखें...", "mux_switch": "MUX स्विच", "gpu_info": "GPU जानकारी",
        "gpu_card": "ग्राफ़िक्स कार्ड", "driver_ver": "ड्राइवर संस्करण", "gpu_mode": "GPU मोड", "hybrid": "हाइब्रिड",
        "discrete": "असतत GPU", "integrated": "एकीकृत GPU", "hybrid_desc": "NVIDIA ऑप्टिमस",
        "discrete_desc": "NVIDIA GeForce", "integrated_desc": "Intel/AMD ग्राफ़िक्स",
        "gpu_checking": "जांच कर रहा है...", "restart_warn": "सिस्टम पुनरारंभ आवश्यक है।",
        "mux_not_found": "MUX उपकरण नहीं मिला", "mux_install_hint": "envycontrol स्थापित होना चाहिए।",
        "restart": "रीस्टार्ट", "restart_confirm": "सिस्टम रीस्टार्ट होगा। जारी रखें?",
        "mode_set": "मोड सेट हो गया। रीस्टार्ट हो रहा है...", "mux_backend_label": "MUX बैकएंड", "mux_auto": "स्वतः पहचानें",
        "appearance": "रूप-रंग", "theme": "थीम", "lang_label": "भाषा", "dark": "डार्क", "light": "लाइट", "system": "सिस्टम",
        "updates": "अपडेट", "current_ver": "वर्तमान संस्करण", "dashboard": "डैशबोर्ड", "quick_status": "त्वरित स्थिति",
        "hardware_profile": "हार्डवेयर प्रोफाइल", "resources": "संसाधन", "quick_actions": "त्वरित कार्य", "clean_memory": "मेमोरी साफ़ करें",
        "max_fan": "MAX फैन", "eco_mode": "इको मोड", "go_performance": "प्रदर्शन पर जाएँ", "fan_metric": "फैन",
        "disk": "डिस्क", "ram": "रैम", "cpu_load_30s": "CPU लोड", "power_profile_label": "पावर",
        "fan_mode_label": "फैन मोड", "gpu_mux_label": "GPU/MUX", "battery": "बैटरी", "ac_power": "पावर",
        "health": "स्वास्थ्य", "power_saver_lbl": "सेवर", "balanced_lbl": "संतुलित", "performance_lbl": "प्रदर्शन",
        "check_update": "अपडेट जांचें", "download": "डाउनलोड", "sys_info": "सिस्टम जानकारी", "computer": "कंप्यूटर", "kernel": "कर्नेल",
        "os_name": "ऑपरेटिंग सिस्टम", "arch": "आर्किटेक्चर", "driver_status": "ड्राइवर", "loaded": "✓ लोड किया गया", "not_loaded": "✗ लोड नहीं हुआ",
        "developer": "डेवलपर", "home_subtitle": "जारी रखने के लिए मॉड्यूल चुनें", "debug_info_title": "डिबग",
        "show_debug_info": "डिबग दिखाएं", "copy_debug_log": "डिबग कॉपी करें", "copied_to_clipboard": "कॉपी हो गया",
        "create_github_issue": "GitHub Issue बनाएं", "cpu_tuning": "CPU ट्यूनिंग", "undervolt": "अंडरवोल्ट",
        "cpu_curves": "CPU कर्व", "custom_curve": "कस्टम कर्व", "tcc_offset": "TCC ऑफसेट",
        "power_tuning": "पावर", "power_tuning_desc": "उन्नत सीमाएँ।",
        "undervolt_label": "CPU अंडरवोल्ट", "undervolt_desc": "प्रोसेसर को ठंडा रखता है।",
        "tcc_label": "TCC सीमा", "tcc_desc": "अधिकतम तापमान कम करता है।",
        "power_limits_label": "पावर लिमिट (PL1/PL2)", "power_limits_desc": "वाट सीमाएँ सेट करें।",
        "pl1_w": "PL1 सीमा (W)", "pl2_w": "PL2 सीमा (W)",
        "apply_power": "लागू करें", "power_applied": "सफलतापूर्वक लागू हुआ।",
        "unsupported_power": "समर्थित नहीं।", "troubleshooting_dump": "समस्या निवारण",
        "thanks_for_using": "धन्यवाद।", "send_to_github": "GitHub पर भेजें", "back": "वापस"
    },
    "ar": {
        "fan": "الأداء", "lighting": "الإضاءة", "mux": "MUX", "settings": "الإعدادات", "keyboard": "الاختصارات", "app_profiles": "التطبيقات",
        "fan_control": "التحكم بالمراوح", "system_status": "حالة النظام", "power_profile": "وضع الطاقة", "fan_mode": "وضع المروحة",
        "fan_curve": "منحنى المروحة", "all_sensors": "كل الحساسات", "fan_disabled": "التحكم غير متاح", "checking": "جاري التحقق...",
        "no_ppd": "لا يوجد PPD", "active_profile": "الوضع النشط", "mode": "الوضع", "active": "نشط", "inactive": "غير نشط",
        "saver": "توفير", "balanced": "متوازن", "performance": "أداء", "auto": "تلقائي", "max": "أقصى", "custom": "مخصص", "standard": "قياسي",
        "curve_desc": "تخصيص سرعة المروحة.", "no_sensor": "لا توجد بيانات",
        "keyboard_lighting": "إضاءة لوحة المفاتيح", "keyboard_light": "إضاءة اللوحة", "zone": "المنطقة", "all_zones": "الكل",
        "effect": "التأثير", "direction": "الاتجاه", "speed": "السرعة", "brightness": "السطوع",
        "static_eff": "ثابت", "breathing": "تنفس", "wave": "موجة", "cycle": "دورة", "ltr": "يسار → يمين", "rtl": "يمين → يسار",
        "win_lock": "قفل مفتاح ويندوز", "keyboard_shortcuts": "اختصارات", "special_keys": "مفاتيح خاصة",
        "omen_key": "مفتاح Omen", "victus_key": "مفتاح Omen", "calc_key": "الآلة الحاسبة", "prt_sc_fix": "إصلاح PrtSc",
        "prt_sc_desc": "إصلاح مفتاح لقطة الشاشة.", "f1_fix": "إصلاح F1",
        "f1_desc": "إصلاح مفتاح F1.", "apply_shortcuts": "تطبيق",
        "shortcuts_desc": "تغيير سلوك بعض المفاتيح.", "hwdb_applied": "تم التطبيق.",
        "macros_title": "الماكرو", "macros_desc": "تعيين أوامر.",
        "term_cmd": "أمر الوحدة الطرفية...", "choose_app": "اختيار تطبيق", "sel_app": "تحديد تطبيق",
        "or_custom_cmd": "أو أدخل أمر bash...", "mux_switch": "مفتاح MUX", "gpu_info": "معلومات GPU",
        "gpu_card": "بطاقة الرسوميات", "driver_ver": "تعريف بطاقة الشاشة", "gpu_mode": "وضع GPU", "hybrid": "مدمج (Hybrid)",
        "discrete": "منفصل", "integrated": "مدمج", "hybrid_desc": "NVIDIA Optimus",
        "discrete_desc": "NVIDIA GeForce", "integrated_desc": "Intel / AMD",
        "gpu_checking": "جاري التحقق...", "restart_warn": "إعادة التشغيل مطلوبة.",
        "mux_not_found": "أداة MUX غير موجودة", "mux_install_hint": "يجب تثبيت envycontrol.",
        "restart": "إعادة التشغيل", "restart_confirm": "سيتم إعادة تشغيل النظام. هل توافق؟",
        "mode_set": "جاري إعادة التشغيل...", "mux_backend_label": "أداة MUX", "mux_auto": "تلقائي",
        "appearance": "المظهر", "theme": "السمة", "lang_label": "اللغة", "dark": "داكن", "light": "فاتح", "system": "النظام",
        "updates": "التحديثات", "current_ver": "الإصدار الحالي", "dashboard": "لوحة القيادة", "quick_status": "الحالة",
        "hardware_profile": "الملف الشخصي", "resources": "الموارد", "quick_actions": "إجراءات", "clean_memory": "تنظيف الذاكرة",
        "max_fan": "مروحة قصوى", "eco_mode": "وضع توفير الطاقة", "go_performance": "الذهاب للأداء", "fan_metric": "مروحة",
        "disk": "قرص", "ram": "الذاكرة", "cpu_load_30s": "معالج CPU", "power_profile_label": "طاقة",
        "fan_mode_label": "وضع المروحة", "gpu_mux_label": "رسوميات", "battery": "بطارية", "ac_power": "شاحن",
        "health": "الصحة", "power_saver_lbl": "توفير", "balanced_lbl": "متوازن", "performance_lbl": "أداء",
        "check_update": "تحديث", "download": "تحميل", "sys_info": "النظام", "computer": "حاسوب", "kernel": "نواة",
        "os_name": "نظام التشغيل", "arch": "هندسة", "driver_status": "التعريفات", "loaded": "✓ محمل", "not_loaded": "✗ غير محمل",
        "developer": "المطور", "home_subtitle": "اختر وحدة للاستمرار", "debug_info_title": "تصحيح الأخطاء",
        "show_debug_info": "عرض التصحيح", "copy_debug_log": "نسخ التصحيح", "copied_to_clipboard": "تم النسخ",
        "create_github_issue": "إنشاء مشكلة GitHub", "cpu_tuning": "تعديل CPU", "undervolt": "خفض الجهد",
        "cpu_curves": "منحنيات CPU", "custom_curve": "مخصص", "tcc_offset": "TCC",
        "power_tuning": "الطاقة", "power_tuning_desc": "إعدادات متقدمة.",
        "undervolt_label": "خفض جهد CPU", "undervolt_desc": "يبرد المعالج.",
        "tcc_label": "حرارة TCC", "tcc_desc": "يقلل الحرارة القصوى.",
        "power_limits_label": "حدود الطاقة", "power_limits_desc": "تعيين حدود واط.",
        "pl1_w": "حد طويل (PL1)", "pl2_w": "حد قصير (PL2)",
        "apply_power": "تطبيق", "power_applied": "تم التطبيق.",
        "unsupported_power": "غير مدعوم.", "troubleshooting_dump": "استكشاف الأخطاء",
        "thanks_for_using": "شكراً لك.", "send_to_github": "إرسال إلى Github", "back": "رجوع"
    }
}
