#!/usr/bin/env python3
"""OMEN Command Center for Linux — ACPI DSDT/SSDT Mapper.

This module dumps the ACPI tables (DSDT, SSDT) from sysfs, decompiles them
using `iasl`, and parses the resulting ASL code to map hardware capabilities
(such as fan control methods, GPU modes, battery controls, and WMI GUIDs).
"""

import os
import re
import shutil
import subprocess
import tempfile
import logging

logger = logging.getLogger("hp-manager.acpi_mapper")

# Well-known ACPI methods/paths we want to check for Omen systems
INTERESTING_METHODS = {
    "FAN1": "Fan 1 Control",
    "FAN2": "Fan 2 Control",
    "FMAX": "Fan Max Speed",
    "TGPP": "GPU TGP Control",
    "PPAB": "GPU PPAB Control",
    "BCLM": "Battery Charge Limit",
    "WMBC": "WMI BIOS Control",
    "WMAB": "WMI AB Control",
    "AMW0": "HP WMI Interface 0",
}

def dump_and_analyze_acpi() -> dict:
    """
    Dumps DSDT and SSDT tables, decompiles them, and analyzes capabilities.
    Returns a dictionary mapping of found features.
    """
    result = {
        "status": "success",
        "acpica_installed": False,
        "dsdt_found": False,
        "methods_found": {},
        "wmi_guids": [],
        "errors": []
    }

    if not shutil.which("iasl"):
        result["status"] = "error"
        result["errors"].append("iasl (acpica-tools) not installed. Cannot decompile ACPI tables.")
        return result
    
    result["acpica_installed"] = True

    dsdt_path = "/sys/firmware/acpi/tables/DSDT"
    if not os.path.exists(dsdt_path):
        result["status"] = "error"
        result["errors"].append("DSDT table not found in /sys/firmware/acpi/tables/")
        return result

    result["dsdt_found"] = True

    with tempfile.TemporaryDirectory(prefix="omenctl_acpi_") as tmpdir:
        tmp_dsdt = os.path.join(tmpdir, "DSDT.dat")
        
        try:
            shutil.copy2(dsdt_path, tmp_dsdt)
        except Exception as e:
            result["status"] = "error"
            result["errors"].append(f"Failed to copy DSDT: {e}")
            return result

        # Decompile DSDT
        try:
            subprocess.run(["iasl", "-d", "DSDT.dat"], cwd=tmpdir, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, timeout=10)
        except Exception as e:
            result["status"] = "error"
            result["errors"].append(f"Failed to decompile DSDT: {e}")
            return result

        dsl_path = os.path.join(tmpdir, "DSDT.dsl")
        if not os.path.exists(dsl_path):
            result["status"] = "error"
            result["errors"].append("DSDT.dsl was not generated by iasl.")
            return result

        # Parse the DSL file
        try:
            with open(dsl_path, "r", encoding="utf-8", errors="ignore") as f:
                content = f.read()

                # Find interesting methods
                for method, description in INTERESTING_METHODS.items():
                    if re.search(r"Method \s*\(" + re.escape(method) + r"\s*\,", content, re.IGNORECASE):
                        result["methods_found"][method] = description
                    elif re.search(r"Name \s*\(" + re.escape(method) + r"\s*\,", content, re.IGNORECASE):
                        result["methods_found"][method] = f"{description} (Name/Property)"

                # Extract WMI GUIDs
                wmi_matches = re.finditer(r"pnp0c14", content, re.IGNORECASE)
                has_wmi = any(wmi_matches)
                if has_wmi:
                    result["methods_found"]["PNP0C14"] = "WMI Mapper Device"

                guid_pattern = r"[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}"
                guids = set(re.findall(guid_pattern, content))
                result["wmi_guids"] = list(guids)

        except Exception as e:
            result["status"] = "error"
            result["errors"].append(f"Error parsing DSDT.dsl: {e}")

    return result

if __name__ == "__main__":
    import json
    print(json.dumps(dump_and_analyze_acpi(), indent=2))
